#!/bin/bash

echo "* Generating coins..."
sleep 5

litecoin-cli -conf=/etc/conf/node-1/litecoin.conf generate 101
litecoin-cli -conf=/etc/conf/node-1/litecoin.conf generate 101

ADDRESS=`litecoin-cli -conf=/etc/conf/node-1/litecoin.conf getnewaddress myaccount`
litecoin-cli -conf=/etc/conf/node-1/litecoin.conf sendtoaddress "$ADDRESS" 50
litecoin-cli -conf=/etc/conf/node-1/litecoin.conf generate 101

sleep 2
echo "sent generated coins to $ADDRESS"

s6-svc -d /var/run/s6/services/generate