#!/bin/bash

echo "* Generating coins..."
sleep 5

litecoin-cli -conf=/etc/conf/node-1/litecoin.conf generate 101 > /dev/null
litecoin-cli -conf=/etc/conf/node-1/litecoin.conf generate 101 > /dev/null

ADDRESS=`litecoin-cli -conf=/etc/conf/node-1/litecoin.conf getnewaddress shop`
litecoin-cli -conf=/etc/conf/node-1/litecoin.conf sendtoaddress "$ADDRESS" 50

echo "sent generated coins to $ADDRESS"

ADDRESS=`litecoin-cli -conf=/etc/conf/node-2/litecoin.conf getnewaddress customer`
litecoin-cli -conf=/etc/conf/node-1/litecoin.conf sendtoaddress "$ADDRESS" 50

echo "sent generated coins to $ADDRESS"

echo "* Generating another coins..."
litecoin-cli -conf=/etc/conf/node-1/litecoin.conf generate 101 > /dev/null
echo "* Done!"

sleep 2

s6-svc -d /var/run/s6/services/generate